// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-DnzolB3_Jgaxs93fbUS3cRz9DqaoVJg',
    appId: '1:801144087057:web:dfd7675e0f56dc598187b0',
    messagingSenderId: '801144087057',
    projectId: 'praktikum-mobile-e30f3',
    authDomain: 'praktikum-mobile-e30f3.firebaseapp.com',
    storageBucket: 'praktikum-mobile-e30f3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwY2LrKAwC2EsPxeG4NGx9iXJHozD2NLo',
    appId: '1:801144087057:android:0d88e8256c9198748187b0',
    messagingSenderId: '801144087057',
    projectId: 'praktikum-mobile-e30f3',
    storageBucket: 'praktikum-mobile-e30f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU7p4OVwf6xXdtKfPK79AtBxPhAk1Wr9k',
    appId: '1:801144087057:ios:0af0ab7a1c7cbff88187b0',
    messagingSenderId: '801144087057',
    projectId: 'praktikum-mobile-e30f3',
    storageBucket: 'praktikum-mobile-e30f3.firebasestorage.app',
    iosBundleId: 'com.praktikum.mobile.praktikum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU7p4OVwf6xXdtKfPK79AtBxPhAk1Wr9k',
    appId: '1:801144087057:ios:0af0ab7a1c7cbff88187b0',
    messagingSenderId: '801144087057',
    projectId: 'praktikum-mobile-e30f3',
    storageBucket: 'praktikum-mobile-e30f3.firebasestorage.app',
    iosBundleId: 'com.praktikum.mobile.praktikum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-DnzolB3_Jgaxs93fbUS3cRz9DqaoVJg',
    appId: '1:801144087057:web:224d154e2499e3f08187b0',
    messagingSenderId: '801144087057',
    projectId: 'praktikum-mobile-e30f3',
    authDomain: 'praktikum-mobile-e30f3.firebaseapp.com',
    storageBucket: 'praktikum-mobile-e30f3.firebasestorage.app',
  );
}
